/*
 * Data API
 * Serves the Clever Data API
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ContactResponse;
import io.swagger.client.model.ContactsResponse;
import io.swagger.client.model.DistrictResponse;
import io.swagger.client.model.NotFound;
import io.swagger.client.model.StudentsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContactsApi
 */
@Ignore
public class ContactsApiTest {

    private final ContactsApi api = new ContactsApi();

    /**
     * 
     *
     * Returns a specific student contact
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContactTest() throws ApiException {
        String id = null;
        ContactResponse response = api.getContact(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a list of student contacts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContactsTest() throws ApiException {
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        String count = null;
        ContactsResponse response = api.getContacts(limit, startingAfter, endingBefore, count);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the district for a student contact
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDistrictForContactTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrictForContact(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the students for a student contact
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStudentsForContactTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        StudentsResponse response = api.getStudentsForContact(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
}
