/*
 * Data API
 * Serves the Clever Data API
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CourseResponse;
import io.swagger.client.model.CoursesResponse;
import io.swagger.client.model.DistrictResponse;
import io.swagger.client.model.NotFound;
import io.swagger.client.model.SectionsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CoursesApi
 */
@Ignore
public class CoursesApiTest {

    private final CoursesApi api = new CoursesApi();

    /**
     * 
     *
     * Returns a specific course
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCourseTest() throws ApiException {
        String id = null;
        CourseResponse response = api.getCourse(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a list of courses
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCoursesTest() throws ApiException {
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        String count = null;
        CoursesResponse response = api.getCourses(limit, startingAfter, endingBefore, count);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the district for a course
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDistrictForCourseTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrictForCourse(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the sections for a Courses
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSectionsForCourseTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SectionsResponse response = api.getSectionsForCourse(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
}
