/*
 * Data API
 * Serves the Clever Data API
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DistrictResponse;
import io.swagger.client.model.DistrictsResponse;
import io.swagger.client.model.NotFound;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DistrictsApi
 */
@Ignore
public class DistrictsApiTest {

    private final DistrictsApi api = new DistrictsApi();

    /**
     * 
     *
     * Returns a specific district
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDistrictTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrict(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a list of districts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDistrictsTest() throws ApiException {
        String count = null;
        DistrictsResponse response = api.getDistricts(count);

        // TODO: test validations
    }
}
