/*
 * Data API
 * Serves the Clever Data API
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DistrictResponse;
import io.swagger.client.model.NotFound;
import io.swagger.client.model.SchoolResponse;
import io.swagger.client.model.SchoolsResponse;
import io.swagger.client.model.SectionsResponse;
import io.swagger.client.model.StudentsResponse;
import io.swagger.client.model.TeachersResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchoolsApi
 */
@Ignore
public class SchoolsApiTest {

    private final SchoolsApi api = new SchoolsApi();

    /**
     * 
     *
     * Returns the district for a school
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDistrictForSchoolTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrictForSchool(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a specific school
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchoolTest() throws ApiException {
        String id = null;
        SchoolResponse response = api.getSchool(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a list of schools
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchoolsTest() throws ApiException {
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        String count = null;
        SchoolsResponse response = api.getSchools(limit, startingAfter, endingBefore, count);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the sections for a school
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSectionsForSchoolTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SectionsResponse response = api.getSectionsForSchool(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the students for a school
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStudentsForSchoolTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        StudentsResponse response = api.getStudentsForSchool(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the teachers for a school
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTeachersForSchoolTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        TeachersResponse response = api.getTeachersForSchool(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
}
