/*
 * Data API
 * Serves the Clever Data API
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DistrictResponse;
import io.swagger.client.model.NotFound;
import io.swagger.client.model.SchoolAdminResponse;
import io.swagger.client.model.SchoolAdminsResponse;
import io.swagger.client.model.SchoolsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchoolAdminsApi
 */
@Ignore
public class SchoolAdminsApiTest {

    private final SchoolAdminsApi api = new SchoolAdminsApi();

    /**
     * 
     *
     * Returns the district for a school admin
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDistrictForSchoolAdminTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrictForSchoolAdmin(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a specific school admin
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchoolAdminTest() throws ApiException {
        String id = null;
        SchoolAdminResponse response = api.getSchoolAdmin(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a list of school admins
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchoolAdminsTest() throws ApiException {
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        String count = null;
        SchoolAdminsResponse response = api.getSchoolAdmins(limit, startingAfter, endingBefore, count);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the schools for a school admin
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchoolsForSchoolAdminTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SchoolsResponse response = api.getSchoolsForSchoolAdmin(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
}
