/*
 * Data API
 * Serves the Clever Data API
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ContactsResponse;
import io.swagger.client.model.DistrictResponse;
import io.swagger.client.model.NotFound;
import io.swagger.client.model.SchoolResponse;
import io.swagger.client.model.SchoolsResponse;
import io.swagger.client.model.SectionsResponse;
import io.swagger.client.model.StudentResponse;
import io.swagger.client.model.StudentsResponse;
import io.swagger.client.model.TeachersResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StudentsApi
 */
@Ignore
public class StudentsApiTest {

    private final StudentsApi api = new StudentsApi();

    /**
     * 
     *
     * Returns the contacts for a student
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContactsForStudentTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        ContactsResponse response = api.getContactsForStudent(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the district for a student
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDistrictForStudentTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrictForStudent(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the primary school for a student
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchoolForStudentTest() throws ApiException {
        String id = null;
        SchoolResponse response = api.getSchoolForStudent(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the schools for a student
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchoolsForStudentTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SchoolsResponse response = api.getSchoolsForStudent(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the sections for a student
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSectionsForStudentTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SectionsResponse response = api.getSectionsForStudent(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a specific student
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStudentTest() throws ApiException {
        String id = null;
        StudentResponse response = api.getStudent(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a list of students
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStudentsTest() throws ApiException {
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        String count = null;
        StudentsResponse response = api.getStudents(limit, startingAfter, endingBefore, count);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the teachers for a student
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTeachersForStudentTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        TeachersResponse response = api.getTeachersForStudent(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
}
