/*
 * Data API
 * Serves the Clever Data API
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DistrictResponse;
import io.swagger.client.model.NotFound;
import io.swagger.client.model.SchoolResponse;
import io.swagger.client.model.SchoolsResponse;
import io.swagger.client.model.SectionsResponse;
import io.swagger.client.model.StudentsResponse;
import io.swagger.client.model.TeacherResponse;
import io.swagger.client.model.TeachersResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeachersApi
 */
@Ignore
public class TeachersApiTest {

    private final TeachersApi api = new TeachersApi();

    /**
     * 
     *
     * Returns the district for a teacher
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDistrictForTeacherTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrictForTeacher(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieves school info for a teacher.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchoolForTeacherTest() throws ApiException {
        String id = null;
        SchoolResponse response = api.getSchoolForTeacher(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the schools for a teacher
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSchoolsForTeacherTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SchoolsResponse response = api.getSchoolsForTeacher(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the sections for a teacher
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSectionsForTeacherTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SectionsResponse response = api.getSectionsForTeacher(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the students for a teacher
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStudentsForTeacherTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        StudentsResponse response = api.getStudentsForTeacher(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a specific teacher
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTeacherTest() throws ApiException {
        String id = null;
        TeacherResponse response = api.getTeacher(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a list of teachers
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTeachersTest() throws ApiException {
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        String count = null;
        TeachersResponse response = api.getTeachers(limit, startingAfter, endingBefore, count);

        // TODO: test validations
    }
}
