/*
 * Data API
 * Serves the Clever Data API
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DistrictResponse;
import io.swagger.client.model.NotFound;
import io.swagger.client.model.SectionsResponse;
import io.swagger.client.model.TermResponse;
import io.swagger.client.model.TermsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TermsApi
 */
@Ignore
public class TermsApiTest {

    private final TermsApi api = new TermsApi();

    /**
     * 
     *
     * Returns the district for a term
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDistrictForTermTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrictForTerm(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns the sections for a term
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSectionsForTermTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SectionsResponse response = api.getSectionsForTerm(id, limit, startingAfter, endingBefore);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a specific term
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTermTest() throws ApiException {
        String id = null;
        TermResponse response = api.getTerm(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Returns a list of terms
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTermsTest() throws ApiException {
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        String count = null;
        TermsResponse response = api.getTerms(limit, startingAfter, endingBefore, count);

        // TODO: test validations
    }
}
